import { ToolMeta } from '@/types/tools';

export const TOOLS: ToolMeta[] = [
  {
    id: 'scratchpad',
    name: 'Scratchpad',
    description: 'Temporary workspace for .env, snippets, SQL, and bash commands',
    category: 'workspace',
    href: '/scratchpad',
    icon: 'Terminal',
    keywords: ['env editor online', 'temporary snippet storage', 'online scratchpad'],
    quickActionLabel: 'Open →',
  },
  {
    id: 'random-secret',
    name: 'Random Secret Generator',
    description: 'Generate secure random strings based on crypto',
    category: 'security',
    href: '/tools/random-secret-generator',
    icon: 'Shield',
    keywords: ['random secret generator', 'crypto random generator', 'base64 secret generator'],
    quickActionLabel: 'Generate →',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure and customizable passwords',
    category: 'security',
    href: '/tools/password-generator',
    icon: 'Lock',
    keywords: ['secure password generator', 'random password generator', 'online password generator'],
    quickActionLabel: 'Generate →',
  },
  {
    id: 'base64-generator',
    name: 'Base64 Generator',
    description: 'Generate random base64 strings for tokens and secrets',
    category: 'crypto',
    href: '/tools/base64-generator',
    icon: 'Key',
    keywords: ['base64 generator', 'random base64 online', 'base64 encode decode'],
    quickActionLabel: 'Open →',
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUID v4 instantly',
    category: 'crypto',
    href: '/tools/uuid-generator',
    icon: 'Fingerprint',
    keywords: ['uuid generator online', 'uuid v4 generator'],
    quickActionLabel: 'Generate →',
  },
  {
    id: 'sha256-generator',
    name: 'SHA256 Generator',
    description: 'Generate SHA256 hash instantly',
    category: 'crypto',
    href: '/tools/sha256-generator',
    icon: 'Hash',
    keywords: ['sha256 generator', 'sha256 hash online'],
    quickActionLabel: 'Generate →',
  },
  {
    id: 'json-php-converter',
    name: 'JSON ⇄ PHP Array Converter',
    description: 'Convert JSON to PHP Array and vice versa',
    category: 'utility',
    href: '/tools/json-php-converter',
    icon: 'RefreshCw',
    keywords: ['json to php array', 'php array to json', 'php array converter'],
    quickActionLabel: 'Convert →',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder & Inspector',
    description: 'Decode, inspect, and analyze JWT tokens locally and securely',
    category: 'security',
    href: '/tools/jwt-decoder',
    icon: 'Eye',
    keywords: ['jwt decoder', 'jwt inspector', 'decode jwt online', 'verify jwt'],
    quickActionLabel: 'Inspect →',
  },
  {
    id: 'curl-builder',
    name: 'cURL Builder & API Playground',
    description: 'Build, import, test, and analyze HTTP requests from your browser',
    category: 'utility',
    href: '/tools/curl-builder',
    icon: 'Globe',
    keywords: ['curl builder', 'api playground', 'online postman', 'test api online'],
    quickActionLabel: 'Play →',
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter & Query Analyzer',
    description: 'Format SQL queries and analyze for dangerous actions or syntax errors',
    category: 'utility',
    href: '/tools/sql-formatter',
    icon: 'Database',
    keywords: ['sql formatter', 'sql query analyzer', 'beautify sql', 'minify sql'],
    quickActionLabel: 'Format →',
  },
];
