import { ToolMeta } from '@/types/tools';

export const TOOLS: ToolMeta[] = [
  {
    id: 'scratchpad',
    name: 'Scratchpad',
    description: 'Temporary workspace for .env, snippets, SQL, and bash commands',
    category: 'workspace',
    href: '/scratchpad',
    icon: 'Terminal',
    keywords: ['env editor online', 'temporary snippet storage', 'online scratchpad'],
    quickActionLabel: 'Open →',
  },
  {
    id: 'random-secret',
    name: 'Random Secret Generator',
    description: 'Generate secure random strings based on crypto',
    category: 'security',
    href: '/tools/random-secret-generator',
    icon: 'Shield',
    keywords: ['random secret generator', 'crypto random generator', 'base64 secret generator'],
    quickActionLabel: 'Generate →',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure and customizable passwords',
    category: 'security',
    href: '/tools/password-generator',
    icon: 'Lock',
    keywords: ['secure password generator', 'random password generator', 'online password generator'],
    quickActionLabel: 'Generate →',
  },
  {
    id: 'base64-generator',
    name: 'Base64 Generator',
    description: 'Generate random base64 strings for tokens and secrets',
    category: 'crypto',
    href: '/tools/base64-generator',
    icon: 'Key',
    keywords: ['base64 generator', 'random base64 online', 'base64 encode decode'],
    quickActionLabel: 'Open →',
  },
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUID v4 instantly',
    category: 'crypto',
    href: '/tools/uuid-generator',
    icon: 'Fingerprint',
    keywords: ['uuid generator online', 'uuid v4 generator'],
    quickActionLabel: 'Generate →',
  },
  {
    id: 'sha256-generator',
    name: 'SHA256 Generator',
    description: 'Generate SHA256 hash instantly',
    category: 'crypto',
    href: '/tools/sha256-generator',
    icon: 'Hash',
    keywords: ['sha256 generator', 'sha256 hash online'],
    quickActionLabel: 'Generate →',
  },
];
